---
output:
  html_document:
    css: D:/analysis/R/tistory/plotly/style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.width = 6.5)

library(showtext)
showtext_auto()
library(tidyverse)
library(readxl)
library(patchwork)
library(plotly)
library(sf)

spdf_shp <- st_read('C:/R/git/datavisualization/chap10/TL_SCCO_CTPRVN.shp', options = 'ENCODING=CP949')

```

사용데이터 : <https://2stndard.tistory.com/107>

## ggspatial을 사용한 지도 꾸미기

지도에는 반드시 표시되어야 하는 몇가지 요소가 있다. 그것중에 모든 지도에 필수적으로 포함되는 요소가 북쪽을 가리키는 표식과 지도의 상대적 크기를 나타내는 축척이다. 이 두가지 요소를 어떻게 넣어야하는지 알아보겠다.

지도를 꾸며주는데 사용하는 패키지는 여러가지가 있지만 여기서는 `ggspatial` 패키지를 사용한다. `ggspatial` 패키지에서 북쪽을 가리키는 나침반 표식을 넣는 함수는 `annotation_north_arrow()`이고 축척을 넣는 함수는 `annotation_scale()` 이다. 

```{r}
if (!require(ggspatial)) {
  install.packages('ggspatial')
  library(ggspatial)
}

spdf_shp |> ggplot() + 
  ## X축을 long(경도), Y축을 lat(위도), group을 group, color를 id로 매핑하고 fill을 white로 설정한 geom_polygon 레이어 생성 
  ## simple feature 객체를 사용하여 geom_sf 레이어를 생성
  geom_sf(fill = "dodgerblue", color = 'white', show.legend = F) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "br", pad_y = unit(0.05, 'npc'),
                         style = north_arrow_nautical) +
  theme_bw()

```

